/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 204));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DASHBOARD");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 177, 55));

        b1.setBackground(new java.awt.Color(255, 255, 204));
        b1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        b1.setText("BOOKS AVAILABLE");
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 187, 177, 44));

        b2.setBackground(new java.awt.Color(255, 255, 204));
        b2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        b2.setText("ADD BOOKS");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 177, 48));

        b3.setBackground(new java.awt.Color(255, 255, 204));
        b3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        b3.setText("REMOVE BOOKS");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 347, 177, 43));

        b4.setBackground(new java.awt.Color(255, 255, 204));
        b4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        b4.setText("STAFF DETAILS");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, 162, 44));

        b5.setBackground(new java.awt.Color(255, 255, 204));
        b5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        b5.setText("ADD STAFF");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        getContentPane().add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, 160, 44));

        b6.setBackground(new java.awt.Color(255, 255, 204));
        b6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        b6.setText("REMOVE STAFF");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        getContentPane().add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, 161, 43));

        b7.setBackground(new java.awt.Color(255, 255, 204));
        b7.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        b7.setText("NEW REGISTRATION");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        getContentPane().add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 210, 120));

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online-library-system.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 550));

        jButton1.setBackground(new java.awt.Color(255, 153, 102));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jButton1.setText("TAKE ME BACK TO THE LOGIN PAGE");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, 492, 45));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public Dashboard() {
        
    initComponents();
     // Add Books button
    b2.addActionListener(evt -> {
        this.dispose(); // Optional: close Dashboard
        new AddBooks().setVisible(true); 
    
// Open AddBooks window
    });

    // Books Available button
    b1.addActionListener(evt -> {
        new BooksAvailable().setVisible(true); // Open BooksAvailable page
        this.dispose(); // Optional: close Dashboard
        
    
    });
    
    b4.addActionListener(evt -> {
        new StaffDetails().setVisible(true);
        this.dispose();
    });
    
    // Add Staff button
b5.addActionListener(evt -> {
    new AddStaffs().setVisible(true); // Open AddStaffs page
    this.dispose(); // Optional: close Dashboard
});

    // Remove Books button
    b3.addActionListener(evt -> {
        new RemoveBooks().setVisible(true); // Open RemoveBooks page
        this.dispose(); // Close Dashboard
    });
    
    // Remove Staff button
b6.addActionListener(evt -> {
    new RemoveStaff().setVisible(true);  // open RemoveStaff window
    this.dispose(); // close Dashboard (optional)
});

// New Registration button
b7.addActionListener(evt -> {
    new NewRegistration().setVisible(true);  // Open NewRegistration window
    this.dispose();  // Optional: close Dashboard
});

jButton1.addActionListener(evt -> {
        new LoginPage().setVisible(true);  // Opens LoginPage.java
        this.dispose();                    // Closes Dashboard window
    });





}

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {                                   
    new BooksAvailable().setVisible(true);  // ✅ Opens BooksAvailable page
    this.dispose();  // Optional: closes Dashboard window
    }

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
